# Generated by Django 5.2.10 on 2026-01-21 18:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('INSPECTION', 'Inspection'), ('TESTING', 'Testing'), ('TRAINING', 'Training'), ('OPERATOR_CERTIFICATION', 'Operator Certification'), ('CALIBRATION', 'Calibration')], max_length=30)),
                ('discipline', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('requires_equipment', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('requires_person', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('checklist_template', models.CharField(blank=True, max_length=150)),
                ('default_checklist_level', models.CharField(choices=[('SIMPLIFIED', 'Simplified'), ('EXPANDED', 'Expanded'), ('CRITICAL', 'Critical')], default='SIMPLIFIED', max_length=20)),
                ('minimum_checklist_level', models.CharField(choices=[('SIMPLIFIED', 'Simplified'), ('EXPANDED', 'Expanded'), ('CRITICAL', 'Critical')], default='SIMPLIFIED', max_length=20)),
                ('allow_bulk_all_ok', models.BooleanField(default=False)),
                ('require_photo_evidence', models.BooleanField(default=False)),
                ('require_document_evidence', models.BooleanField(default=False)),
                ('sticker_policy', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_APPLICABLE', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('approver_roles', models.JSONField(blank=True, default=list, help_text='List of approver role names')),
                ('validity_max_months', models.PositiveIntegerField(blank=True, null=True)),
                ('validity_options', models.JSONField(blank=True, default=list, help_text='Allowed validity options in months')),
                ('output_definitions', models.JSONField(blank=True, default=list, help_text='Controlled outputs for the service')),
                ('standards', models.JSONField(blank=True, default=list, help_text='Linked standards or procedures')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'service_versions',
                'ordering': ['service', '-version_number'],
            },
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='approvals_entity__d57650_idx',
            old_name='approvals_entity_type_entity_id_idx',
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='approvals_approve_c3a582_idx',
            old_name='approvals_approver_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_entity__d4c2e5_idx',
            old_name='audit_logs_entity_type_entity_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_88267f_idx',
            old_name='audit_logs_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_qr_code_c455b1_idx',
            old_name='certificates_qr_code_idx',
        ),
        migrations.RenameIndex(
            model_name='certificate',
            new_name='certificate_share_l_23d319_idx',
            old_name='certificates_share_link_token_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_name_0bc5f0_idx',
            old_name='clients_name_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_email_4c8bec_idx',
            old_name='clients_email_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_tag_cod_ea0bd4_idx',
            old_name='equipment_tag_code_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_serial__ac559e_idx',
            old_name='equipment_serial_number_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_client__8e2bdb_idx',
            old_name='equipment_client_next_due_idx',
        ),
        migrations.RenameIndex(
            model_name='inspection',
            new_name='inspections_inspect_940da1_idx',
            old_name='inspections_inspector_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inspection',
            new_name='inspections_status_dcaadc_idx',
            old_name='inspections_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='joborder',
            new_name='job_orders_client__c1a4f9_idx',
            old_name='job_orders_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='joborder',
            new_name='job_orders_status_b61819_idx',
            old_name='job_orders_status_scheduled_start_idx',
        ),
        migrations.RenameIndex(
            model_name='photoref',
            new_name='photo_refs_inspect_51fb86_idx',
            old_name='photo_refs_inspection_slot_name_idx',
        ),
        migrations.RenameIndex(
            model_name='sticker',
            new_name='stickers_sticker_474af2_idx',
            old_name='stickers_sticker_code_idx',
        ),
        migrations.RenameIndex(
            model_name='sticker',
            new_name='stickers_status_436bfb_idx',
            old_name='stickers_status_idx',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='swl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Safe Working Load', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inspections.service'),
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inspections.serviceversion'),
        ),
        migrations.AddIndex(
            model_name='serviceversion',
            index=models.Index(fields=['service', 'version_number'], name='service_ver_service_2a016e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceversion',
            index=models.Index(fields=['service', 'is_published'], name='service_ver_service_aa3e6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceversion',
            unique_together={('service', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='services_code_5c47ad_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'status'], name='services_categor_65aebe_idx'),
        ),
    ]
