# Generated by Django 6.0.1 on 2026-01-23 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_service_serviceversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipline', models.CharField(blank=True, help_text='Discipline or subcategory for this authorization', max_length=120)),
                ('level', models.CharField(choices=[('SUPERVISED', 'Supervised'), ('AUTHORIZED', 'Authorized'), ('LEAD', 'Lead')], default='SUPERVISED', max_length=15)),
                ('scope_notes', models.TextField(blank=True, help_text='Additional scope notes or limitations')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_authorizations', to='inspections.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competence_authorizations',
                'ordering': ['user', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('TRAINING', 'Training'), ('CERTIFICATE', 'Certificate'), ('ASSESSMENT', 'Assessment'), ('OTHER', 'Other')], default='TRAINING', max_length=15)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='competence_evidence/')),
                ('notes', models.TextField(blank=True)),
                ('authorization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='inspections.competenceauthorization')),
            ],
            options={
                'db_table': 'competence_evidence',
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('person_type', models.CharField(choices=[('OPERATOR', 'Operator'), ('TRAINEE', 'Trainee'), ('CLIENT_STAFF', 'Client Staff'), ('INTERNAL', 'Internal Staff')], default='OPERATOR', max_length=20)),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_people', to='inspections.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_name', models.CharField(max_length=150)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('reference_code', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=12)),
                ('document', models.FileField(blank=True, null=True, upload_to='people_credentials/')),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='inspections.person')),
            ],
            options={
                'db_table': 'person_credentials',
                'ordering': ['person', '-issued_on'],
            },
        ),
        migrations.AddIndex(
            model_name='competenceauthorization',
            index=models.Index(fields=['user', 'status'], name='competence__user_id_c8c190_idx'),
        ),
        migrations.AddIndex(
            model_name='competenceauthorization',
            index=models.Index(fields=['service', 'discipline'], name='competence__service_713a86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competenceauthorization',
            unique_together={('user', 'service', 'discipline', 'level', 'valid_from')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type'], name='people_person__f63f58_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['client', 'person_type'], name='people_client__5a048f_idx'),
        ),
        migrations.AddIndex(
            model_name='personcredential',
            index=models.Index(fields=['person', 'status'], name='person_cred_person__0cd3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='personcredential',
            index=models.Index(fields=['valid_until'], name='person_cred_valid_u_7cddfb_idx'),
        ),
    ]
