# Generated by Django 6.0.1 on 2026-01-24 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_competenceauthorization_competenceevidence_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('LOSS', 'Loss'), ('DAMAGE', 'Damage'), ('CALIBRATION_FAILURE', 'Calibration Failure'), ('OTHER', 'Other')], max_length=25)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('occurred_on', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tool_incidents',
                'ordering': ['-occurred_on'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CHECKOUT', 'Check-out'), ('CHECKIN', 'Check-in'), ('CALIBRATION', 'Calibration'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('ALERT', 'Alert')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tool_usage_logs',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='assignment_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('JOB_ORDER', 'Job Order'), ('POOL', 'Shared Pool')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('MAINTENANCE', 'Maintenance'), ('CALIBRATION', 'Under Calibration'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=15),
        ),
        migrations.CreateModel(
            name='ToolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('USER', 'User'), ('JOB_ORDER', 'Job Order'), ('EQUIPMENT', 'Equipment'), ('CLIENT', 'Client Contact')], max_length=15)),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='ACTIVE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assignments', to='inspections.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assignments', to='inspections.equipment')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assignments', to='inspections.joborder')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inspections.tool')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tool_assignments',
                'ordering': ['-assigned_on'],
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('requires_calibration', models.BooleanField(default=False)),
                ('calibration_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_assignment_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('JOB_ORDER', 'Job Order'), ('POOL', 'Shared Pool')], default='INDIVIDUAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tool Categories',
                'db_table': 'tool_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inspections.toolcategory'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['status'], name='tools_status_c7bf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category', 'status'], name='tools_categor_6bb89d_idx'),
        ),
        migrations.AddField(
            model_name='toolincident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolincident',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='inspections.tool'),
        ),
        migrations.AddField(
            model_name='toolincident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusagelog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='inspections.toolassignment'),
        ),
        migrations.AddField(
            model_name='toolusagelog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_usage_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolusagelog',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='inspections.tool'),
        ),
        migrations.AddIndex(
            model_name='toolassignment',
            index=models.Index(fields=['tool', 'status'], name='tool_assign_tool_id_3175b9_idx'),
        ),
        migrations.AddIndex(
            model_name='toolassignment',
            index=models.Index(fields=['assignment_type', 'status'], name='tool_assign_assignm_fc169c_idx'),
        ),
        migrations.AddIndex(
            model_name='toolusagelog',
            index=models.Index(fields=['tool', 'event_type'], name='tool_usage__tool_id_9aa866_idx'),
        ),
    ]
